//! D1 data-access layer.
//!
//! Each sub-module owns one table-group.  All queries are parameterized
//! (no string concatenation — RFC-012 §9.6).  IDs are generated by the
//! caller; D1 stores them as TEXT.

pub mod community;
pub mod invite;
pub mod membership;
pub mod session;

use worker::{D1Database, Result};

/// Thin wrapper so callers don't import worker types directly.
pub type Db<'a> = &'a D1Database;

/// Current UTC timestamp as ISO-8601 string for D1 TEXT columns.
pub fn now_utc() -> String {
    // Workers runtime exposes Date.now() via JS interop; we use
    // the worker::Date shim which wraps it.
    let ms = worker::Date::now().as_millis();
    // Format: "2026-06-12T00:00:00.000Z"
    let secs = ms / 1000;
    let millis = ms % 1000;
    let (y, mo, d, h, mi, s) = epoch_to_ymd_hms(secs);
    format!("{y:04}-{mo:02}-{d:02}T{h:02}:{mi:02}:{s:02}.{millis:03}Z")
}

/// Add `seconds` to a UTC ISO-8601 string produced by `now_utc()`.
pub fn add_seconds_to_now(seconds: u64) -> String {
    let ms = worker::Date::now().as_millis() + seconds * 1000;
    let secs = ms / 1000;
    let millis = ms % 1000;
    let (y, mo, d, h, mi, s) = epoch_to_ymd_hms(secs);
    format!("{y:04}-{mo:02}-{d:02}T{h:02}:{mi:02}:{s:02}.{millis:03}Z")
}

// Minimal epoch decomposition without the `time` crate (avoids wasm32 TZ issues).
fn epoch_to_ymd_hms(epoch_secs: u64) -> (u32, u32, u32, u32, u32, u32) {
    let s = epoch_secs % 60;
    let m = (epoch_secs / 60) % 60;
    let h = (epoch_secs / 3600) % 24;
    let days = epoch_secs / 86400;
    // Gregorian calendar decomposition (valid for years 1970–2099)
    let mut z = days + 719468;
    let era = z / 146097;
    let doe = z % 146097;
    let yoe = (doe - doe / 1460 + doe / 36524 - doe / 146096) / 365;
    let y = yoe + era * 400;
    let doy = doe - (365 * yoe + yoe / 4 - yoe / 100);
    let mp = (5 * doy + 2) / 153;
    let d = doy - (153 * mp + 2) / 5 + 1;
    let mo = if mp < 10 { mp + 3 } else { mp - 9 };
    let y = if mo <= 2 { y + 1 } else { y };
    // suppress unused warning on z
    let _ = z;
    (y as u32, mo as u32, d as u32, h as u32, m as u32, s as u32)
}
